version: '3.8'

services:
  chroma:
    image: chromadb/chroma:latest
    container_name: chroma_db
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_AUTH_CREDENTIALS=test-token
      - CHROMA_SERVER_AUTH_PROVIDER=token
      - CHROME_SERVER_HTTP_ALLOWED_ORIGINS=*
      - CHROMA_SERVER_NO_TLS=true
    volumes:
      - chroma_data:/chroma/chroma
    restart: unless-stopped

volumes:
  chroma_data:
